#-*- coding: utf-8 -*-

DEVICE_TOKEN_ID = 1
PAYLOAD_ID = 2
NOTIFICATION_IDENTIFIER_ID = 3
EXPIRATION_DATE_ID = 4
PRIORITY_ID = 5

NO_ERROR_HAPPENED = 0
PROCESSING_ERROR = 1
MISSING_DEVICE_TOKEN = 2
MISSING_TOPIC = 3
MISSING_PAYLOAD = 4
INVALID_TOKEN_SIZE = 5
INVALID_TOPIC_SIZE = 6
INVALID_PAYLOAD_SIZE = 7
INVALID_TOKEN = 8
SHUTDOWN = 10
UNKNOWN_ERROR = 255

APNS_READ_WAIT = 0.5
APNS_READ_BUF_SIZE = 6
APNS_HOST = "gateway.push.apple.com"
APNS_SANDBOX_HOST = "gateway.sandbox.push.apple.com"
APNS_PORT = 2195
APNS_FEEDBACK_HOST = "feedback.push.apple.com"
APNS_FEEDBACK_SANDBOX_HOST = "feedback.sandbox.push.apple.com"
APNS_FEEDBACK_PORT = 2196
APNS_FEEDBACK_TOKEN_LENGTH = 32
APNS_FEEDBACK_BLOCK_SIZE = 38
APNS_FEEDBACK_BUFFER_SIZE = 3800
