##target lib###
CXX=g++
TARGET=apush_server
FUNSHION_LIB := ../../../../../../Library/funshion/lib
LOGINSERVER_LIB := ../lib
DEST_ETC := ../bin/etc/
DEST_LOG := ../bin/log/

LIB := $(LOGINSERVER_LIB)/libmgmt.a
LIB += $(LOGINSERVER_LIB)/libservice.a
LIB += $(LOGINSERVER_LIB)/libvisitor.a
LIB += $(LOGINSERVER_LIB)/libctrl.a
LIB += $(LOGINSERVER_LIB)/libconfig.a
LIB += $(LOGINSERVER_LIB)/libutil.a
LIB += $(LOGINSERVER_LIB)/libnetsvc.a
LIB += $(LOGINSERVER_LIB)/libuser_mgr.a
LIB += $(LOGINSERVER_LIB)/libencrypt.a
LIB += $(LOGINSERVER_LIB)/libhttp.a
LIB += $(LOGINSERVER_LIB)/libhttp.a
#LIB += $(LOGINSERVER_LIB)/libjson_linux-gcc-4.1.2_libmt.a
LIB += $(LOGINSERVER_LIB)/libjsoncpp.a
#LIB += ./json/0.1.1/src/libjson.a
LIB += $(FUNSHION_LIB)/kernel/0.1.2/libkernel.a
LIB += $(FUNSHION_LIB)/msgq/0.1.0/libmsgq.a 
LIB += $(FUNSHION_LIB)/logger/0.2.0/liblogger.a
LIB += $(FUNSHION_LIB)/timer/0.1.0/libtimer.a 
LIB += $(FUNSHION_LIB)/thread/0.1.0/libthread.a 
LIB += $(FUNSHION_LIB)/zlib/1.2.4/libz.a
LIB += $(FUNSHION_LIB)/boost/linux_64/libboost_filesystem.a
LIB += $(FUNSHION_LIB)/boost/linux_64/libboost_system.a
LIB += $(FUNSHION_LIB)/boost/linux_64/libboost_thread.a




HEADER_DIR := ../../../../../../Library/funshion/include/boost/boost_1_40/
HEADER_DIR += ../../../../../../Library/funshion/include/kernel/0.1.2/
HEADER_DIR += ../../../../../../Library/funshion/include/logger/0.2.0/
HEADER_DIR += ../../../../../../Library/funshion/include/thread/0.1.0/
HEADER_DIR += ../../../../../../Library/funshion/include/timer/0.1.0 /
HEADER_DIR += ../../../../../../Library/funshion/include/msgq/0.1.0/
#HEADER_DIR += ./json/0.1.1/src/include
#HEADER_DIR += ./json/0.1.1/jsoncpp-src-0.5.0/include
HEADER_DIR += util/include/
HEADER_DIR += user_mgr/include/
HEADER_DIR += netsvc/include/
HEADER_DIR += config/include/
HEADER_DIR += http/include/
HEADER_DIR += ctrl/include/
HEADER_DIR += visitor/include/
HEADER_DIR += mgmt/include/
HEADER_DIR += service/include/
HEADER_DIR += ../include/
HEADER_DIR += ./include/


INCLUDE := $(addprefix -I ,$(HEADER_DIR)) 

CXXFLAGS :=${flags} -DMAKEFILEBUILD_DATE="\"`date '+%Y-%m-%d %H:%M:%S'`"\"

SRCS := $(wildcard *.cpp $(SRCDIR)/*.cpp)
OBJS := $(patsubst %.cpp,%.o,$(SRCS))

$(TARGET):$(OBJS)
	$(CXX) $(CXXFLAGS) $^ -o $@  $(LIB)  -lpthread -lm -lrt
	cp $(TARGET) ../bin/
	-@if [ ! -d ${DEST_ETC} ]; then mkdir -p ${DEST_ETC}; fi
	-@if [ ! -d ${DEST_LOG} ]; then mkdir -p ${DEST_LOG}; fi
	#cp -f ../etc/* $(DEST_ETC)

$(OBJS):%.o:%.cpp 
	$(CXX) $(INCLUDE) $(CXXFLAGS) -c $< -o $@    

echo:
	echo $(SRCS)
clean:
	-rm -rf $(TARGET) *.o	

check:
	cppcheck -j 4 --enable=all $(INCLUDE) -f -q . 2>cppcheck.log

